version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    depends_on:
      - jaeger
      - postgresql
  postgresql:
    image: postgresql
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  cargo_app:
    build: .
    ports:
      - "11111:11111"